function GM:PrecacheContent()
	
	util.PrecacheModel( "models/items/ammopack_medium.mdl" )
	util.PrecacheModel( "models/bots/headless_hatman.mdl" )
	util.PrecacheModel( "models/weapons/c_models/c_bigaxe/c_bigaxe.mdl" )
	util.PrecacheModel( "models/weapons/w_models/w_grenade_grenadelauncher.mdl" )
	util.PrecacheModel( "models/weapons/w_models/w_grenade_grenadelauncher.mdl" )
	util.PrecacheModel( "models/items/medkit_medium.mdl" )
	util.PrecacheModel( "models/props_doomsday/cap_point_small.mdl" )
	util.PrecacheModel( "models/weapons/w_models/w_rocket.mdl" )
	util.PrecacheModel( "models/bots/skeleton_sniper/skeleton_sniper.mdl" )
	util.PrecacheModel( "models/weapons/c_models/c_dumpster_device/c_dumpster_device.mdl" )
	util.PrecacheModel( "models/player/items/sniper/veteran_hat.mdl" )
	util.PrecacheModel( "models/weapons/c_models/c_tfc_sniperrifle/c_tfc_sniperrifle.mdl" )
	util.PrecacheModel( "models/player/items/sniper/dotasniper_hat.mdl" )
	util.PrecacheModel( "models/player/items/sniper/skull_horns_b3.mdl" )
	util.PrecacheModel( "models/player/items/all_class/trn_wiz_hat_sniper.mdl" )
	util.PrecacheModel( "models/items/crystal_ball_pickup.mdl" )
	
	
	util.PrecacheSound( "items/ammo_pickup.wav" )
	util.PrecacheSound( "weapons/halloween_boss/knight_axe_hit.wav" )
	util.PrecacheSound( "misc/flame_engulf.wav" )
	util.PrecacheSound( "weapons/explode1.wav" )
	util.PrecacheSound( "weapons/explode2.wav" )
	util.PrecacheSound( "weapons/explode3.wav" )
	util.PrecacheSound( "items/smallmedkit1.wav" )
	util.PrecacheSound( "weapons/bumper_car_jump.wav" )
	util.PrecacheSound( "weapons/air_burster_shoot.wav" )
	util.PrecacheSound( "weapons/sniper_rifle_classic_shoot.wav" )
	util.PrecacheSound( "weapons/iceaxe/iceaxe_swing1.wav" )
	util.PrecacheSound( "weapons/fist_hit_world1.wav" )
	util.PrecacheSound( "weapons/fist_hit_world2.wav" )
	util.PrecacheSound( "weapons/capper_shoot.wav" )
	util.PrecacheSound( "ui/hitsound.wav" )
	util.PrecacheSound( "weapons/dragons_fury_impact.wav" )
	util.PrecacheSound( "weapons/cleaver_hit_02.wav" )
	util.PrecacheSound( "weapons/samurai/tf_katana_slice_03.wav" )
	util.PrecacheSound( "weapons/csgo_awp_shoot.wav" )
	util.PrecacheSound( "weapons/grappling_hook_shoot.wav" )
	
	util.PrecacheSound( "vo/halloween_boss/knight_spawn.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack01.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack02.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack03.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack04.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_laugh01.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_laugh02.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_laugh03.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_laugh04.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack01.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack02.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack03.mp3" )
	util.PrecacheSound( "vo/halloween_boss/knight_attack04.mp3" )
	util.PrecacheSound( "music/hl1_song10.mp3" )
	util.PrecacheSound( "music/hl1_song15.mp3" )
	util.PrecacheSound( "music/hl1_song17.mp3" )
	util.PrecacheSound( "music/hl1_song25_remix3.mp3" )
	util.PrecacheSound( "music/hl2_song3.mp3" )
	util.PrecacheSound( "music/hl2_song4.mp3" )
	util.PrecacheSound( "music/hl2_song12_long.mp3" )
	util.PrecacheSound( "music/hl2_song14.mp3" )
	util.PrecacheSound( "music/hl2_song20_submix0.mp3" )
	util.PrecacheSound( "music/hl2_song20_submix4.mp3" )
	util.PrecacheSound( "music/hl2_song29.mp3" )
	util.PrecacheSound( "music/hl2_song31.mp3" )
	
end